name: "Check PR Spell"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pr-spell-check:
    uses: oomol/workflows/.github/workflows/cspell-check.yml@v0
    secrets: inherit
    with:
      pr-title: true
      pr-body: true
      code: false
